name: Markdown Lint

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli@0.42.0

      - name: Run markdownlint
        run: |
          markdownlint "**/*.md" --ignore node_modules --ignore .git --config .markdownlint.jsonc || exit 1
